# Generated by Django 5.1.6 on 2025-02-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FA3',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('slno', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('eng', models.IntegerField()),
                ('kan', models.IntegerField()),
                ('hin', models.IntegerField()),
                ('maths', models.IntegerField()),
                ('sci', models.IntegerField()),
                ('soc_sci', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FA4',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('slno', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('eng', models.IntegerField()),
                ('kan', models.IntegerField()),
                ('hin', models.IntegerField()),
                ('maths', models.IntegerField()),
                ('sci', models.IntegerField()),
                ('soc_sci', models.IntegerField()),
            ],
        ),
    ]
