# Generated by Django 5.1.6 on 2025-02-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_fa3_fa4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fa1',
            name='eng',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='fa2',
            name='eng',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='fa3',
            name='eng',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='fa4',
            name='eng',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
